window.galleryPhotos = [
  [
    "alberobello.jpg",
    "Alberobello",
    "Italia",
    "Casas blancas tradicionales en Alberobello, Italia",
    "alberobello",
  ],
  [
    "arrozChina.JPG",
    "Arrozales",
    "China",
    "Paisaje de arrozales durante un viaje por China",
    "arroz-china",
  ],
  ["bled.JPG", "Bled", "Eslovenia", "Vista de Bled en Eslovenia", "bled"],
  [
    "bruselas.jpg",
    "Bruselas",
    "Bélgica",
    "Escena urbana de Bruselas, Bélgica",
    "bruselas",
  ],
  [
    "budapestIglesia.JPG",
    "Budapest",
    "Hungría",
    "Iglesia y arquitectura de Budapest, Hungría",
    "budapest-iglesia",
  ],
  [
    "casaChina.JPG",
    "Casa tradicional",
    "China",
    "Casa tradicional fotografiada en China",
    "casa-china",
  ],
  [
    "casaDinamarca.JPG",
    "Costa nórdica",
    "Dinamarca",
    "Casa junto a la costa en Dinamarca",
    "casa-dinamarca",
  ],
  [
    "cascadaEslovenia.JPG",
    "Agua clara",
    "Eslovenia",
    "Cascada de agua clara en Eslovenia",
    "cascada-eslovenia",
  ],
  [
    "castilloDinamarca.JPG",
    "Castillo",
    "Dinamarca",
    "Castillo fotografiado durante un viaje por Dinamarca",
    "castillo-dinamarca",
  ],
  [
    "edimburgo.JPG",
    "Edimburgo",
    "Escocia",
    "Vista de Edimburgo en Escocia",
    "edimburgo",
  ],
  [
    "letrasChina.JPG",
    "Letras y color",
    "China",
    "Detalle con letras y color en China",
    "letras-china",
  ],
  [
    "lubliana.jpg",
    "Liubliana",
    "Eslovenia",
    "Rincón de Liubliana, Eslovenia",
    "lubliana",
  ],
  [
    "rioCina2.JPG",
    "Reflejos",
    "China",
    "Vista de rio y reflejos durante un viaje por China",
    "rio-cina2",
  ],
  [
    "manSeaDinamarca.JPG",
    "Frente al mar",
    "Dinamarca",
    "Persona mirando al mar en Dinamarca",
    "man-sea-dinamarca",
  ],
  [
    "objetoChina.JPG",
    "Detalle",
    "China",
    "Detalle decorativo fotografiado en China",
    "objeto-china",
  ],
  [
    "parlamento.jpg",
    "Parlamento",
    "Budapest",
    "Parlamento de Budapest junto al rio",
    "parlamento",
  ],
  [
    "pula.JPG",
    "Pula",
    "Croacia",
    "Arquitectura y calle de Pula, Croacia",
    "pula",
  ],
  [
    "rioChina.JPG",
    "Rio",
    "China",
    "Rio y paisaje urbano en China",
    "rio-china",
  ],
  [
    "piedrasErraticas.JPG",
    "Piedras erráticas",
    "Estonia",
    "Vista al Mar Báltico con piedras erráticas",
    "piedras-erraticas",
  ],
  [
    "treeSisters.JPG",
    "Three Sisters",
    "Escocia",
    "Montañas con cumbres neblinosas",
    "three-sisters",
  ],
  [
    "frankfurt.JPG",
    "Frankfurt",
    "Alemania",
    "Centro histórico con casas tradicionales",
    "frankfurt",
  ],
];
